class AppLocalizations {
  static const Map<String, Map<String, String>> translations = {
    'en': {
      'login': 'Login',
      'welcome': 'Welcome to Setu',
      'phone_number': 'Phone Number',
      'password': 'Password',
      'savings': 'Savings',
      'skills': 'Skills',
      'loans': 'Loans',
      'meetings': 'Meetings',
      'dashboard': 'Dashboard',
    },
    'hi': {
      'login': 'लॉग इन करें',
      'welcome': 'सेतु में आपका स्वागत है',
      'phone_number': 'फ़ोन नंबर',
      'password': 'पासवर्ड',
      'savings': 'बचत',
      'skills': 'कौशल',
      'loans': 'ऋण',
      'meetings': 'बैठकें',
      'dashboard': 'डैशबोर्ड',
    },
    'bn': {
      'login': 'লগ ইন করুন',
      'welcome': 'সেতুতে স্বাগতম',
      'phone_number': 'ফোন নম্বর',
      'password': 'পাসওয়ার্ড',
      'savings': 'সঞ্চয়',
      'skills': 'দক্ষতা',
      'loans': 'ঋণ',
      'meetings': 'মিটিং',
      'dashboard': 'ড্যাশবোর্ড',
    },
    'te': {
      'login': 'లాగిన్ చేయండి',
      'welcome': 'సేతుకు స్వాగతం',
      'phone_number': 'ఫోన్ నంబర్',
      'password': 'పాస్‌వర్డ్',
      'savings': 'పొదుపు',
      'skills': 'నైపుణ్యాలు',
      'loans': 'రుణాలు',
      'meetings': 'సమావేశాలు',
      'dashboard': 'డాష్‌బోర్డ్',
    },
    'mr': {
      'login': 'लॉग इन करा',
      'welcome': 'सेतूमध्ये आपले स्वागत आहे',
      'phone_number': 'फोन नंबर',
      'password': 'पासवर्ड',
      'savings': 'बचत',
      'skills': 'कौशल्ये',
      'loans': 'कर्ज',
      'meetings': 'बैठका',
      'dashboard': 'डॅशबोर्ड',
    },
    'ta': {
      'login': 'உள்நுழையவும்',
      'welcome': 'சேதுவுக்கு வருக',
      'phone_number': 'தொலைபேசி எண்',
      'password': 'கடவுச்சொல்',
      'savings': 'சேமிப்பு',
      'skills': 'திறன்கள்',
      'loans': 'கடன்கள்',
      'meetings': 'கூட்டங்கள்',
      'dashboard': 'முகப்பு',
    },
    'ur': {
      'login': 'لاگ ان کریں',
      'welcome': 'سیتو میں خوش آمدید',
      'phone_number': 'فون نمبر',
      'password': 'پاس ورڈ',
      'savings': 'بچت',
      'skills': 'مہارتیں',
      'loans': 'قرضے',
      'meetings': 'ملاقاتیں',
      'dashboard': 'ڈیش بورڈ',
    },
    'gu': {
      'login': 'લોગ ઇન કરો',
      'welcome': 'સેતુમાં તમારું સ્વાગત છે',
      'phone_number': 'ફોન નંબર',
      'password': 'પાસવર્ડ',
      'savings': 'બચત',
      'skills': 'કૌશલ્યો',
      'loans': 'લોન',
      'meetings': 'મીટિંગ્સ',
      'dashboard': 'ડેશબોર્ડ',
    },
    'kn': {
      'login': 'ಲಾಗಿನ್ ಮಾಡಿ',
      'welcome': 'ಸೇತುಗೆ ಸುಸ್ವಾಗತ',
      'phone_number': 'ಫೋನ್ ಸಂಖ್ಯೆ',
      'password': 'ಪಾಸ್‌ವರ್ಡ್',
      'savings': 'ಉಳಿತಾಯ',
      'skills': 'ಕೌಶಲ್ಯಗಳು',
      'loans': 'ಸಾಲಗಳು',
      'meetings': 'ಸಭೆಗಳು',
      'dashboard': 'ಡ್ಯಾಶ್‌ಬೋರ್ಡ್',
    },
    'or': {
      'login': 'ଲଗ୍ ଇନ୍ କରନ୍ତୁ',
      'welcome': 'ସେତୁକୁ ସ୍ୱାଗତ',
      'phone_number': 'ଫୋନ୍ ନମ୍ବର',
      'password': 'ପାସୱାର୍ଡ',
      'savings': 'ସଞ୍ଚୟ',
      'skills': 'ଦକ୍ଷତା',
      'loans': 'ଋଣ',
      'meetings': 'ମିଟିଂ',
      'dashboard': 'ଡ୍ୟାସବୋର୍ଡ',
    },
    'ml': {
      'login': 'ലോഗിൻ ചെയ്യുക',
      'welcome': 'സേതുവിലേക്ക് സ്വാഗതം',
      'phone_number': 'ഫോൺ നമ്പർ',
      'password': 'പാസ്‌വേഡ്',
      'savings': 'സമ്പാദ്യം',
      'skills': 'കഴിവുകൾ',
      'loans': 'വായ്പകൾ',
      'meetings': 'യോഗങ്ങൾ',
      'dashboard': 'ഡാഷ്‌ബോർഡ്',
    },
    'pa': {
      'login': 'ਲਾਗਇਨ ਕਰੋ',
      'welcome': 'ਸੇਤੂ ਵਿੱਚ ਜੀ ਆਇਆਂ ਨੂੰ',
      'phone_number': 'ਫੋਨ ਨੰਬਰ',
      'password': 'ਪਾਸਵਰਡ',
      'savings': 'ਬਚਤ',
      'skills': 'ਹੁਨਰ',
      'loans': 'ਕਰਜ਼ੇ',
      'meetings': 'ਮੀਟਿੰਗਾਂ',
      'dashboard': 'ਡੈਸ਼ਬੋਰਡ',
    },
    'as': {
      'login': 'লগ ইন কৰক',
      'welcome': 'সেতুলৈ স্বাগতম',
      'phone_number': 'ফোন নম্বৰ',
      'password': 'পাছৱৰ্ড',
      'savings': 'সঞ্চয়',
      'skills': 'দক্ষতা',
      'loans': 'ঋণ',
      'meetings': 'মিটিং',
      'dashboard': 'ডেশবৰ্ড',
    },
  };

  static String translate(String key, String langCode) {
    return translations[langCode]?[key] ?? translations['en']?[key] ?? key;
  }
}
